# Generated by Django 5.0.3 on 2024-04-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('profilephoto', models.ImageField(upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('producttype', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('B', 'BOY'), ('G', 'GIRL'), ('C', 'COMMON')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('offerprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('dateposted', models.DateTimeField(auto_now_add=True)),
                ('productphoto1', models.ImageField(upload_to='products')),
                ('productphoto2', models.ImageField(blank=True, upload_to='products')),
                ('productphoto3', models.ImageField(blank=True, upload_to='products')),
                ('productphoto4', models.ImageField(blank=True, upload_to='products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kart.userdatabase')),
            ],
        ),
    ]
