# Generated by Django 5.0.3 on 2024-04-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0003_alter_kart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kart',
            old_name='quantity',
            new_name='veruthe',
        ),
    ]
