# Generated by Django 5.0.3 on 2024-04-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0004_rename_quantity_kart_veruthe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kart',
        ),
    ]
