# Generated by Django 5.0.3 on 2024-04-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0007_kart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kart',
        ),
    ]
