# Generated by Django 5.0.3 on 2024-04-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0009_kart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kart',
        ),
    ]
