# Generated by Django 5.0.3 on 2024-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0011_kart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
