# Generated by Django 5.0.3 on 2024-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0013_alter_kart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
