# Generated by Django 5.0.3 on 2024-04-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0014_alter_kart_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kart',
        ),
    ]
