# Generated by Django 5.0.3 on 2024-05-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0018_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address',
            new_name='addressmodel',
        ),
    ]
