# Generated by Django 5.0.3 on 2024-05-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0020_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
