# Generated by Django 5.0.3 on 2024-05-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0024_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
