# Generated by Django 5.0.3 on 2024-05-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0026_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kart',
        ),
    ]
