# Generated by Django 5.0.3 on 2024-05-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0028_kart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
